"""initial migration

Revision ID: 3512fbd48618
Revises: 
Create Date: 2024-10-18 14:41:41.800926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3512fbd48618'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_time', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['completed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completion_time')
        batch_op.drop_column('completed_by_id')

    # ### end Alembic commands ###
