"""Added legacy id to order

Revision ID: d60d729d1394
Revises: 3512fbd48618
Create Date: 2025-02-04 22:31:08.944660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60d729d1394'
down_revision = '3512fbd48618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['legacy_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('legacy_id')

    # ### end Alembic commands ###
